### ISSUE TITLE
How to automatically place the human in the scenes?

### ISSUE THREAD

**Issue by eugenelyj** [PerceivingSystems/bedlam_render#1]
Congratulations for your awesome work!
I am curious about how you automatically place the human in the scenes? Can i access to the code of this part?

**Comment by tpsmpi** [comment]
Please see corresponding [README.md](https://github.com/PerceivingSystems/bedlam_render/blob/main/tools/sequence_generation/README.md) for details.
Additional information can be found in the supplementary materials of the paper which you can download from BEDLAM website.
