### ISSUE TITLE
What is BE_CameraRoot in Level?

### ISSUE THREAD

**Issue by cqx28402** [PerceivingSystems/bedlam_render#10]
Hi,
when I prepare target Level map before generates sequences, I want to create a Level contains following actors:
- ``BE_CineCameraActor_Blueprint`` attached to empty ``BE_CameraRoot actor``
- ``BE_GroundTruthLogger``

I can find ``BE_CineCameraActor_Blueprint`` and ``BE_GroundTruthLogger`` in ``core`` file, but I don't know what is ``BE_CameraRoot actor``.
In fact, I can create LevelSequences without adding ``BE_CameraRoot actor`` to Level and render the movie successfully.
I'm confused about it. Thanks

**Comment by tpsmpi** [comment]
`BE_CameraRoot` is an empty Actor at origin. It is used to setup up a simple camera rig for basic orbiting. Is is used for sequences where you want to randomize the camera location/rotation for each sequence for static cameras which are offset from the target center and should face the center area.
See `cameraroot` option in [be_modify_sequences.py](https://github.com/PerceivingSystems/bedlam_render/blob/main/tools/sequence_generation/be_modify_sequences.py) for details.

**Comment by cqx28402** [comment]
I understand now. Thank you for your answer.
