### ISSUE TITLE
Body textures rendering

### ISSUE THREAD

**Issue by cqx28402** [PerceivingSystems/bedlam_render#11]
Hi,
I have prepared body textures and materials in `UE_5.0\Engine\Content\PS\Meshcapade\SMPL`  and the corresponding texture_clothing was identified in the be_seq.csv file. However, body textures do not appear in the created LevelSequences. How can I add body textures correctly?
Thanks in advance

**Comment by tpsmpi** [comment]
Please check the Unreal Editor Output Log for relevant error messages.
If you resolved the issue in the meantime then please leave a comment for others how you resolved it before closing the issue.

**Comment by cqx28402** [comment]
Thank you for your answer.
The Unreal Editor Output Log shows no error, which indicates that the materials was loaded successfully, but the materials does not display body textures.
The problem seems to be in the create body materials step, where I get the exact same materials.
![image](https://github.com/PerceivingSystems/bedlam_render/assets/106021358/7fc662ff-ece2-4152-b711-22be06a81463)
I followed the instructions again and got the same result.

**Comment by tpsmpi** [comment]
It looks like you have issues generating the body material instance assets.
You need to check the Output Log when you run https://github.com/PerceivingSystems/bedlam_render/blob/main/unreal/import/create_body_materials.py.
If you look at the script you will see that it skips existing materials instances so you need to delete existing faulty ones before rerunning. Also make sure that your Bedlam Core assets are installed first as mentioned in the import README.

**Comment by cqx28402** [comment]
Thank you very much for your answer.
It looks like I made a bug with changes to Core assets before, and I re-downloaded the Core folder and placed it in ```PS\Bedlam``` to get the correct body materials.
Now I can render a textured body!
