### ISSUE TITLE
Metric of depth image

### ISSUE THREAD

**Issue by YuxuanSnow** [PerceivingSystems/bedlam_render#14]
Hi,

i have a question regarding the metric of the provided depth frames. I randomly load one .ext depth image, and found that the average depth value is 1.2e8. I wonder what is the unit of this value and if it's possible to convert to more common metric like meter?

Thanks!

**Comment by tpsmpi** [comment]
Depth is stored as 32-bit float in Unreal coordinate system units: `[cm]`
Useful tool for examinining `.exr` depth values: https://github.com/afichet/openexr-viewer
