### ISSUE TITLE
Issue with import_clothing_textures.py - Asset not found in registry after import

### ISSUE THREAD

**Issue by niuzehai** [PerceivingSystems/bedlam_render#16]
Dear author,

I encountered an issue when using your import_clothing_textures.py script. The script reports an error when importing textures:

Error: LoadAsset failed: The AssetData '/Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/T_rp_aaron_posed_002_texture_01_diffuse.T_rp_aaron_posed_002_texture_01_diffuse' could not be found in the Asset Registry.

This seems to be because the script is trying to load an asset that doesn't exist. I suspect there may be a bug here, where the script forgets to update the asset registry after importing the textures.

Could you please help look into this issue? Let me know if you need any more information from me to reproduce the problem.

Thanks for publishing this useful script. Resolving this issue would likely help many users.

**Comment by niuzehai** [comment]
**Here's the log.**

LogPython: D:\bedlam_render\unreal\import\import_clothing_textures.py
LogPython: ============================================================
LogPython: Running: D:/bedlam_render/unreal/import/import_clothing_textures.py
LogPython: Processing C:\clothing_textures\rp_aaron_posed_002\clothing_textures\texture_01\texture_01_diffuse_1001.png
LogPython:   Importing: /Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/T_rp_aaron_posed_002_texture_01_diffuse
LogPython:   Importing: /Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/T_rp_aaron_posed_002_texture_01_normal
LogAssetTools: Warning: Interchange do not use the DestinationName parameter. Users must specify the destination name in a pipeline through the Options parameter.
LogInterchangeEngine: [Pending] Importing
LogInterchangeEngine: Display: Interchange start importing source [C:/clothing_textures..._textures/texture_01/texture_01_diffuse_1001.png]
LogCore: PNG has complex alpha channel, will not fill RGB in transparent background, due to setting PNGInfill == OnlyOnBinaryTransparency
Message dialog closed, result: Ok, title: Unable to Check Out From Revision Control!, text: The following assets could not be successfully checked out from revision control:
/Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_diffuse
LogFileHelpers: InternalPromptForCheckoutAndSave started...
LogTexture: Display: Building textures: /Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_diffuse.texture_01_diffuse (TFO_AutoDXT, 4096x4096 x1x1x1) (Required Memory Estimate: 1152.062484 MB), EncodeSpeed: Fast
LogTexture: Display: Waiting for textures to be ready 0/1 (/Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_diffuse) ...
LogSavePackage: Moving output files for package: /Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_diffuse
LogSavePackage: Moving 'C:/Users/DG2023/Documents/Unreal Projects/我的项目/Saved/texture_01_diffuseDCB8E36740EA76EF2AFA11A72E376251.tmp' to '../../../Engine/Content/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_diffuse.uasset'
LogFileHelpers: InternalPromptForCheckoutAndSave took 387 ms (total: 8.72 sec)
Message dialog closed, result: Ok, title: Unable to Check Out From Revision Control!, text: The following assets could not be successfully checked out from revision control:
/Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_diffuse
LogInterchangeEngine: [Success] Import Done
LogAssetTools: Warning: Interchange do not use the DestinationName parameter. Users must specify the destination name in a pipeline through the Options parameter.
LogInterchangeEngine: [Pending] Importing
LogInterchangeEngine: Display: Interchange start importing source [C:/clothing_textures..._textures/texture_01/texture_01_normal_1001.png]
LogInterchangePipeline: Display: Auto-detected normal map
Message dialog closed, result: Ok, title: Unable to Check Out From Revision Control!, text: The following assets could not be successfully checked out from revision control:
/Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_normal
LogFileHelpers: InternalPromptForCheckoutAndSave started...
LogTexture: Display: Building textures: /Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_normal.texture_01_normal (TFO_BC5, 4096x4096 x1x1x1) (Required Memory Estimate: 1152.062484 MB), EncodeSpeed: Fast
LogTexture: Display: Waiting for textures to be ready 0/1 (/Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_normal) ...
LogSavePackage: Moving output files for package: /Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_normal
LogSavePackage: Moving 'C:/Users/DG2023/Documents/Unreal Projects/我的项目/Saved/texture_01_normalE93E85C148CE2F3C6668238AD2298AA5.tmp' to '../../../Engine/Content/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_normal.uasset'
LogFileHelpers: InternalPromptForCheckoutAndSave took 491 ms (total: 9.21 sec)
Message dialog closed, result: Ok, title: Unable to Check Out From Revision Control!, text: The following assets could not be successfully checked out from revision control:
/Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_normal
LogInterchangeEngine: [Success] Import Done
**LogEditorAssetSubsystem: Error: LoadAsset failed: The AssetData '/Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/T_rp_aaron_posed_002_texture_01_diffuse.T_rp_aaron_posed_002_texture_01_diffuse' could not be found in the Asset Registry.**
LogPython: Error: Cannot load texture: /Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/T_rp_aaron_posed_002_texture_01_diffuse
AssetCheck: New page: Asset Save: multiple assets
LogContentValidation: Display: Validating /Script/Engine.Texture2D /Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_diffuse.texture_01_diffuse
LogContentValidation: Display: Validating /Script/Engine.Texture2D /Engine/PS/Bedlam/Clothing/Materials/rp_aaron_posed_002/texture_01_normal.texture_01_normal
LogInterchangeEngine: [Success] Import Done
LogInterchangeEngine: [Success] Import Done

**Comment by dff180** [comment]
Use Unreal Engine 5.0 for this script, it will let you import assets with the desired target name. See also #15 for supported engine versions.

**Comment by tpsmpi** [comment]
It looks like you use Unreal Engine > 5.0.
Use Unreal Engine 5.0 for this script, it will let you import assets with the desired target name. See also #15 for supported engine versions.

**Comment by niuzehai** [comment]
Dear tpsmpi,

I'm writing to express my sincere gratitude for your prompt and helpful response regarding the issue I had encountered with import_clothing_textures.py.

Your suggestion to use Unreal Engine 5.0 for the script resolved the problem perfectly. The assets are now importing with the correct target names. I understand based on your note about supported engine versions that active compatibility is for the specific Unreal version called out in the project requirements. I appreciate you clarifying this for me.

I'm very grateful for your support and for sharing this useful tool with the community. Please accept my thanks once again for your time and assistance in resolving this issue smoothly.
