### ISSUE TITLE
Seeking Guidance on Accessing Ground Truth Camera and SMPL Parameters

### ISSUE THREAD

**Issue by niuzehai** [PerceivingSystems/bedlam_render#18]
I am currently trying to understand how to obtain the camera's intrinsic and extrinsic parameters, as well as the **SMPL-X Ground Truth parameters for an image** within UE 5.0.3. This information is crucial for my project, and I am seeking guidance on the best practices or methods to access these parameters.

**Attempts and Research**
I have explored the documentation and various forums, but have not found a clear methodology or example that fits my use case.

**Questions**
Are there built-in functions or plugins in UE 5.0.3 that allow for the extraction of camera intrinsic and extrinsic parameters?
What is the recommended approach for accessing SMPL parameters for a given image?

Any guidance, references to documentation, or examples would be greatly appreciated.

Thank you in advance for your time and assistance.

**Comment by tpsmpi** [comment]
The ground truth data is logged in the `ground_truth` folder in `.csv` format. This assumes that you use the `BE_GroundTruthLogger` and follow the steps outlined in the `Usage` section at https://github.com/PerceivingSystems/bedlam_render/tree/main/unreal/render

Coordinate system for logged data is Unreal coordinate system.

To further process this data into a more ML friendly format see #4 and the related info in our [BEDLAM ML repo](https://github.com/pixelite1201/BEDLAM/blob/master/data_processing/ReadMe.md)

**Comment by niuzehai** [comment]
Dear tpsmpi,

Thank you very much for your prompt and detailed response. Your guidance has been instrumental in resolving my queries regarding the extraction of camera and SMPL-X Ground Truth parameters in Unreal Engine 5.0.3.

I followed your advice and explored the BE_GroundTruthLogger within the BEDLAM Render Control. The logging of ground truth data in the .csv format in the ground_truth folder, as mentioned in the Usage section at [BEDLAM Render](https://github.com/PerceivingSystems/bedlam_render/tree/main/unreal/render), was exactly what I needed.

Furthermore, I delved into the [BEDLAM ML repo](https://github.com/pixelite1201/BEDLAM/blob/master/data_processing/ReadMe.md) and found the functions for processing the data into a machine learning-friendly format to be very helpful. Specifically, the functions for converting camera intrinsic parameters ([link](https://github.com/pixelite1201/BEDLAM/blob/master/data_processing/df_full_body.py#L72)), camera extrinsic parameters ([link](https://github.com/pixelite1201/BEDLAM/blob/master/data_processing/df_full_body.py#L356-L360)), as well as accessing the Beta ([link](https://github.com/pixelite1201/BEDLAM/blob/master/data_processing/df_full_body.py#L338)) and Poses ([link](https://github.com/pixelite1201/BEDLAM/blob/master/data_processing/df_full_body.py#L362-L366)) parameters, have been particularly valuable.

Your assistance not only solved my immediate problem but also enhanced my understanding of handling such data in Unreal Engine for deep learning applications. I appreciate your time and effort in providing this crucial information.

Thank you once again for your invaluable help.
