### ISSUE TITLE
Guidance Needed on Importing and Aligning Hair Assets from Character Creator to UE 5.0.3

### ISSUE THREAD

**Issue by niuzehai** [PerceivingSystems/bedlam_render#19]
I am currently working with Unreal Engine 5.0.3 and facing challenges in integrating hair assets into my project.

**Issue**
BEDLAM_RENDER project currently lacks hair assets, and I am considering using commercial assets from Character Creator (CC). I need guidance on how to import these hair assets into UE 5.0.3 and align them correctly with character heads.

**Specific Questions**
Importing from CC to UE: What is the recommended workflow for importing hair assets from Character Creator into Unreal Engine? Are there specific formats or settings that ensure compatibility and maintain quality?

Alignment with Head: Once imported, what are the best practices for aligning the hair assets with the character's head in UE 5.0.3? Are there tools or techniques within UE or CC that facilitate precise alignment?

Tutorials and Resources: Are there any tutorials, documentation, or community resources that provide step-by-step instructions or best practices for this process?

**Attempts and Research**
I have noted the potential commercial nature of hair assets, but am unsure of the process and best practices for their utilization in UE 5.0.3.
My current knowledge of importing and aligning assets in UE is limited, prompting this request for guidance.
Any insights, resources, or examples from the community would be immensely helpful. I am open to exploring different methods or tools to achieve a realistic and accurate integration of hair assets into my UE project.

Thank you in advance for your support and advice.

**Comment by tpsmpi** [comment]
Please make sure to check the Dataset Creation section of the paper for details on `hair`. Observed limitations with CC hair cards are discussed in the paper and also the supplementary material section ([arXiv](https://arxiv.org/abs/2306.16940)).

Note that we are no longer using CC software for hair and are moving to [strand based hair grooms](https://docs.unrealengine.com/5.0/en-US/hair-rendering-and-simulation-in-unreal-engine/) which are well supported in latest Blender/Unreal.
We suggest you further explore this area but cannot provide support for this here.

Some more historic details on the CC hair pipeline used for BEDLAM with the available tools as of 2022.

+ CC 4.0.1

+ Alignment of CC template mesh vertices to SMPL-X v1.1 female/male target mesh and reimport of adjusted template into CC4
  + See paper
  + Blender 3.1.2
  + CC to Blender: cc_blender_tools (https://github.com/soupday/cc_blender_tools, 1.3.8)
  + This step is necessary for short hair styles but might not be needed for volumetric hairstyles where simple translation+scaling might be sufficient
  + [There might be better options for this in CC now](https://www.reallusion.com/character-creator/headshot/default.html#mesh-mode)

+ Unreal hair materials (CC to UE):
  + CC Auto Setup 1.25: https://www.reallusion.com/auto-setup/unreal-engine/ 

+ Blender virtual toupee hair mesh alignment for Unreal head node attachment
  + CC to Blender: cc_blender_tools (https://github.com/soupday/cc_blender_tools, 1.3.8)
  + Blender (3.1.2)
    + Align imported hair card mesh to head joint node location of default SMPL-X character and export to Unreal via FBX to preserve potential vertex color information needed by the CC Unreal shaders

+ Use Unreal Skeletal Mesh Animations Sequences for attaching toupee to animated head node
  + Generate FBX animations from `.npz` animation data via [SMPL-X Blender add-on](https://gitlab.tuebingen.mpg.de/jtesch/smplx_blender_addon) (20220623 or later) and import into Unreal as animations.
  + Sample code snippet
```
    # Import animation, do not create keyframed pose correctives for faster import.
    bpy.ops.object.smplx_add_animation(filepath=str(smplx_animation_path), anim_format="SMPL-X", keyframe_corrective_pose_weights=False, target_framerate=30)

    # Export FBX with baked shape and without pose correctives
    output_path.parent.mkdir(parents=True, exist_ok=True)
    bpy.ops.object.smplx_export_fbx(filepath=str(output_path), export_shape_keys="NONE", target_format="UNREAL")
```

**Comment by niuzehai** [comment]
Dear tpsmpi,

I am writing to express my deepest gratitude for your comprehensive and detailed response to my query about integrating hair assets into Unreal Engine 5.0.3 using Character Creator (CC).

Your explanation, especially the insights on transitioning from CC hair cards to strand-based hair grooms supported in the latest Blender/Unreal, has been incredibly enlightening. The reference to the Dataset Creation section of the paper, as well as the supplementary material on arXiv, provided the necessary context and background for understanding the limitations and possibilities with CC hair assets.

Furthermore, the historic details on the CC hair pipeline and the recommended tools and processes, including CC 4.0.1, Blender 3.1.2, and the cc_blender_tools, are invaluable. The step-by-step breakdown for aligning and importing hair assets, along with the usage of Unreal hair materials and the specific Blender virtual toupee hair mesh alignment technique, has given me a clear pathway to follow.

Your suggestion to explore the area of strand-based hair grooms and the provided resources for CC to UE workflows have effectively resolved my concerns and opened up new avenues for my project's development.

I truly appreciate the time and effort you took to provide such an in-depth response. Your expertise and guidance have been instrumental in advancing my project.

Thank you once again for your invaluable support and for sharing your knowledge so generously.
