### ISSUE TITLE
Simulated clothing data

### ISSUE THREAD

**Issue by BlackFox16** [PerceivingSystems/bedlam_render#2]
Hi,
thanks for the great work.

Will the script for generating clothing npz files also be released? Such that I can follow your data generation pipeline.

npz: each file contains
- vertices_seq: float array of shape (n_frames x n_vertices x 3) containing the position of the vertices of the garment mesh for each frame
- faces: int array of shape (n_faces x 3) containing the connectivity information of the mesh
- vertices_uv: float array of shape (n_vertices_uv x 2) containing the position of the vertices in UV space
- faces_uv: int array of shape (n_faces x 3) containing the connectivity of the vertices in UV space
metadata: a dictionary with keys
- fps: framerate of the simulation data contained in the npz file
- source_fps: framerate at which the data was simulated (30 FPS)
- start_frame: first frame of the sequence in the respective 30 FPS Alembic file
- end_frame: last frame of the sequence in the respective 30 FPS Alembic file

This would be helpful. Thanks!

**Comment by xiexh20** [comment]
Thanks for the great work. 

I am also quite interested in the clothing simulation pipeline. Any help is greatly appreciated, thank you very much!

**Comment by gfgb** [comment]
Hi everyone, 

A tutorial and a few scripts will be made available soon. I will link them on the website and give you an update under this GitHub issue.

**Comment by gfgb** [comment]
Hi,

We are uploading in this [repo](https://github.com/PerceivingSystems/bedlam_clothing) the code for the clothing processing part of BEDLAM. It is still work in progress and there is not much right now, but you can find [a script](https://github.com/PerceivingSystems/bedlam_clothing/blob/main/scripts/abc_to_npz.py) for converting an Alembic file to npz as specified on the website.
I will upload the clothing pipeline tutorials there as well when they are ready.

**Comment by stedevelop1** [comment]
Thanks a lot!
