### ISSUE TITLE
Inquiry Regarding the Generation of Clothing Simulation .abc Files for Custom Motions in UE 5.0.3

### ISSUE THREAD

**Issue by niuzehai** [PerceivingSystems/bedlam_render#20]
Dear Author,

I hope this message finds you well. I am currently working on integrating custom motions in npz format into Unreal Engine 5.0.3, following the workflow and standards outlined in your documentation. Your guidance has been invaluable in my progress thus far, and I'm reaching out for a bit more assistance.

Background
I have managed to understand and implement the format for custom motions as follows:

```
**Custom Motion (npz)**
motion_info: (6,) 'squat' '27' '/path/to/mosh_results/smplx_neutral/dataset/subject/motion.npz' '250.0' '3776' '5703'
betas: (10,) scale: 0.1
poses: (T, 165) scale: e-02~1
global_ori: (T, 3) scale: e-02
trans: (T, 3) scale: e-02~1
mocap_frame_rate: 30
gender: female

```

This is compatible with UE5 via Blender, resulting in .abc files.

**Challenge**
My current challenge lies in generating clothing simulation .abc files. Despite downloading the CLO3D project files, the process of creating the clothing simulation part remains unclear to me.

**Queries**
Clothing Simulation Creation: Could you please guide me on the steps or requirements for creating clothing simulation .abc files? Is there a specific methodology using CLO3D or another tool that I should follow?

Skill Requirement: Does the creation of these files necessitate extensive 3D modeling skills, or can it be accomplished with the tools and scripts that are currently available?

Utilizing BEDLAM Clothing Code: I noticed the [BEDLAM Clothing GitHub repository](https://github.com/PerceivingSystems/bedlam_clothing) and was wondering if this code is integral to the clothing simulation process. If so, any advice on how to use this resource effectively would be highly appreciated.

I understand that these queries might be quite specific, but any guidance, no matter how small, would be incredibly helpful. Your expertise in this field is a great resource for individuals like myself.

Thank you very much for your time and consideration.

**Comment by tpsmpi** [comment]
Please ask questions regarding clothing simulation at the [bedlam_clothing](https://github.com/PerceivingSystems/bedlam_clothing) repo.

**Comment by niuzehai** [comment]
Dear tpsmpi,

Thank you for your prompt reply. I appreciate your direction to address my questions regarding clothing simulation at the bedlam_clothing repository.

I will follow your advice and reach out there for further guidance. It’s clear that keeping inquiries specific to the relevant repositories ensures more focused and expert responses, and I am grateful for your suggestion.

Thank you once again for your time and assistance. Your continuous support and guidance are greatly appreciated.
