### ISSUE TITLE
Inquiry Regarding the clothing simulation

### ISSUE THREAD

**Issue by jdyjjj** [PerceivingSystems/bedlam_render#21]
Dear Author,

I saw your pipeline in your paper as shown in the following picture:
![image](https://github.com/PerceivingSystems/bedlam_render/assets/73057174/eb5cee64-2fed-4ff0-a91f-942273af3e89)
But I couldn't find the code for the process from b to c(clothing simulation) in your code repository. Could you please give me some help with this issue? I would be extremely grateful.

**Comment by tpsmpi** [comment]
Clothing design and simulation was done in https://www.clo3d.com/en/
Please ask clothing simulation related questions at the [bedlam_clothing](https://github.com/PerceivingSystems/bedlam_clothing) repo (see #20).
