### ISSUE TITLE
Inquiry about interpenetration between body and clothing

### ISSUE THREAD

**Issue by leizhu-angus** [PerceivingSystems/bedlam_render#22]
Dear author,

We followed your instructions and generated some sample videos. We found that there exists interpenetration between body and clothing in most people as shown in the attached photo, do you know any possible reasons or some ways to improve them? Thank you in advance.
<img width="712" alt="截屏2023-12-13 13 52 38" src="https://github.com/PerceivingSystems/bedlam_render/assets/116175307/57b84c58-635b-4315-bc01-fa4736a2524c">
![coll](https://github.com/PerceivingSystems/bedlam_render/assets/116175307/e227634d-2455-4dd1-b6af-0934845f5244)

**Comment by Usagiu** [comment]
Zoom in the clothes along the normal direction

**Comment by tpsmpi** [comment]
Please provide exact details on how to reproduce the issue in a simplified test case.
+ Which version of Unreal are you using? Is it Unreal 5.0.3?
+ Did you use the animations and clothing simulations we provided as part of BEDLAM without further modification?
  + Then we need to know which exact subject animation and clothing the image is using and also the corresponding `be_seq.csv` you are using.

**Comment by leizhu-angus** [comment]
We are using 5.0.3 and also using assets you provided. The image is using seq_11_5, rp_aaron_posed_009_1001 animation and clothing, the corresponding csv is attached.
[be_seq.csv](https://github.com/PerceivingSystems/bedlam_render/files/13657860/be_seq.csv)

**Comment by tpsmpi** [comment]
Are you rendering via Unreal Sequencer and Movie Render Queue? This is critical for proper sync between animated body and animated clothing.

Can you also reproduce the issue when you render in the `BE_IBL` sample project with one of our HDRI sample scene ground truth `be_seq.csv` files (example: `20221010_3_1000_batch01hand`)?

**Comment by tpsmpi** [comment]
We checked `rp_aaron_posed_009_1001` and it does not show the issue in your sample image.
Did you look into our suggestions and were you able to resolve the issue on your side?
If yes then it would be great if you could leave a comment on how you resolved it and close the issue.

**Comment by tpsmpi** [comment]
Closing inactive issue.

**Comment by tpsmpi** [comment]
Closing inactive issue.

**Comment by tpsmpi** [comment]
Closing inactive issue.
