### ISSUE TITLE
BE_HDRIBackdrop Rotation

### ISSUE THREAD

**Issue by maurb** [PerceivingSystems/bedlam_render#24]
I encountered a problem with the custom component BE_HDRIBackdrop. I tried rotating it in the sequence generation after adding the HDRI. When I select the scene and click on the BE_HDRIBackdrop actor, the new rotation is applied correctly in its transform-properties. However, in the preview window and when rendering the scene, the rotation isn't applied. If I manually change any value in BE_HDRIBackdrop (not just rotation), the component seems to update correctly in the preview window and when rendering.

To fix this issue, I tried applying the rotation to the SceneComponent of BE_HDRIBackdrop instead, which also didn't work.

Do you have any ideas on how to fix this problem?

Thank you!

**Comment by tpsmpi** [comment]
We recommend to rotate the camera and bodies in world space around Unreal world Z-axis when using the HDRI backdrop and not use the HDRIBackdrop Actor rotation.
This world space rotation approach will also give you more world space camera and body location data variation.

You can use `be_modify_sequences.py` with the `sequenceroot` option to accomplish this:

Relevant source: https://github.com/PerceivingSystems/bedlam_render/blob/2976b99e20c95661451677457e9c57e00e9fceb2/tools/sequence_generation/be_modify_sequences.py#L201

**Comment by maurb** [comment]
Thank you!
