### ISSUE TITLE
Erros when  creating MovingRenderQueue

### ISSUE THREAD

**Issue by dnqf11** [PerceivingSystems/bedlam_render#25]
Thanks for your great work. I have done every steps , and created LevelSequence. But I can‘t Create MovieRenderQueue. 
The report is:
LogPython: Error:   Ignoring (no LevelSequence): EditorUtilityWidgetBlueprint /Engine/PS/Bedlam/Core/EditorScripting/BEDLAM.BEDLAM

**Comment by dnqf11** [comment]
selection = unreal.EditorUtilityLibrary.get_selected_assets() # Loads all selected assets into memory
Core/Python/create_movie_render_queue.py line197 
There is only /Engine/PS/Bedlam/Core/EditorScripting/BEDLAM.BEDLAM in selection

**Comment by tpsmpi** [comment]
According to your report you have selected the BEDLAM editor widget asset in the Content Browser and not a `LevelSequence` when trying to generate the movie render queue. You need to select the `LevelSequences` which you want to render out.

Usage instructions at https://github.com/PerceivingSystems/bedlam_render/tree/main/unreal/render
+ `Select desired subset of LevelSequences in Content Browser`

**Comment by dnqf11** [comment]
I have solved this issue. Thank you very much. Additional, can this solution of render can deal with fbx rather than abc?

**Comment by tpsmpi** [comment]
Closing. Please do not ask unrelated questions in issue topic as requested in our issue tracker guidelines.
