### ISSUE TITLE
Some unclear information of BEDLAM SMPLX annotations

### ISSUE THREAD

**Issue by mks0601** [PerceivingSystems/bedlam_render#26]
Hi,

Thanks for your amazing work.
Could you help me to clarify some information about your dataset?

1. The facial expression code of SMPL-X fittings are not provided. The paper says they are set to zero, so can I simply set them to zero when using this dataset?

2. I'm using SMPL-X fitting in `[Images and GT labels](https://bedlam.is.tue.mpg.de/imagesgt.php)` of `Synthetic Image Data at 6fps used for training and testing` in the Download section of the BEDLAM webpage. It seems they provide gender information, but if I use the gendered smplx layer, the projection is wrong. Instead, if I use neutral smplx layer by ignoring the provided gender information, the projections are correct. So should I ignore the gender information of those annotation files and use neutral gender?

3. It seems the file of the second question incldues AGORA images and annotations. Do all AGORA images are included?

**Comment by tpsmpi** [comment]
We recommend that you post your above questions to our BEDLAM ML GitHub repo:
[https://github.com/pixelite1201/BEDLAM](https://github.com/pixelite1201/BEDLAM)

It's a better target location for your issues since bedlam_render repo covers solely the rendering part.

**Comment by mks0601** [comment]
Awesome. Thanks!

**Comment by tpsmpi** [comment]
https://github.com/pixelite1201/BEDLAM/issues/55
