### ISSUE TITLE
egocentric perspective

### ISSUE THREAD

**Issue by Oocean35** [PerceivingSystems/bedlam_render#30]
Hello,

First, thank you for releasing the rendering code and Bedlam dataset , they’re incredibly valuable!

I would like adapt it to an egocentric perspective (with fisheye lenses). Since the pipeline uses geometry caches, I’d like to know what changes are needed in the camera settings to simulate this perspective, and whether these adjustments are possible given the dataset's pipeline setup.

Thanks for any help!

**Comment by tpsmpi** [comment]
The use of geometry caches should not affect the possible camera options.

Egocentric perspective with fisheye lenses is beyond the scope of this repository. 
We recommend to look at this work: 

https://4dqv.mpi-inf.mpg.de/UnrealEgo/
