### ISSUE TITLE
Body textures

### ISSUE THREAD

**Issue by xnd-r** [PerceivingSystems/bedlam_render#5]
Hi, 

I'm trying to go through your [instruction](https://github.com/PerceivingSystems/bedlam_render/tree/main/unreal/import#body-textures) regarding importing data to unreal. 
I have downloaded `bedlam_body_textures_meshcapade`, but it looks like this is not the data I need to use in [create_body_materials.py](https://github.com/PerceivingSystems/bedlam_render/blob/main/unreal/import/create_body_materials.py).
Could you please figure out how to import body textures correctly?

Thanks!

**Comment by tpsmpi** [comment]
We've updated instructions for body texture import in latest commit (92da527). 
As part of this commit the BEDLAM Unreal Core assets have been updated so make sure to update your Unreal Engine install of the BEDLAM Unreal Core assets to latest version.

**Comment by xnd-r** [comment]
Thank you!
