### ISSUE TITLE
create_level_sequences_csv.py

### ISSUE THREAD

**Issue by xnd-r** [PerceivingSystems/bedlam_render#6]
Hi,

I'm trying to render bodies in Unreal Engine. I have prepared all necessary assets according to the instructions (see the spoiler).
<details>
<summary>Engine\Content\PS hierarcy</summary>

- Bedlam
  - Clothing
    - rp_janna_posed_044
      - rp_janna_posed_044_1002_clo.uasset
      - ...
      - rp_janna_posed_044_1099_clo.uasset
  - Core
    - BE_CineCameraActor_Blueprint.uasset
    - BE_GroundTruthLogger.uasset
    - EditorScripting
      - BEDLAM.uasset
    - Materials
      - BE_ClothingOverlayActor.uasset
      - M_Clothing.uasset
      - M_SMPLX.uasset
      - M_SMPLX_Clothing.uasset
      - M_SMPLX_Hidden.uasset
      - M_SMPLX_White.uasset
      - LightProbe
        - BE_LightProbe.uasset
        - BE_LightProbe_Black.uasset
        - BE_LightProbe_Chrome.uasset
        - BE_LightProbe_Gray.uasset
        - BE_LightProbe_White.uasset
        - BE_Skin1.uasset
        - BE_Skin6.uasset
      - Textures
        - rp_aaron_posed_002_texture_01.uasset
        - T_rp_aaron_posed_002_texture_01_diffuse.uasset
        - T_rp_aaron_posed_002_texture_01_normal.uasset
        - Meshcapade_CC_BY-NC_4_0
          - skin_m_white_01_ALB.uasset
          - SMPLX_eye.uasset
    - Python
      - create_level_sequences_csv.py
      - create_movie_render_queue.py
      - render_movie_render_queue.py
  - HDRI
    - 4k
      - decor_shop.uasset
      - small_workshop.uasset
  - SMPLX
    - female_25_it_4002
      - female_25_it_4002_0000.uasset
      - ...
    - male_30_nl_6559
      - male_30_nl_6559_0000.uasset
      - ...
      - male_30_nl_6559_0024.uasset
- Meshcapade
  - SMPL
    - skin_f_african_01_ALB.uasset
    - ...
    - skin_m_white_07_ALB.uasset
    - Materials
      - MI_skin_f_african_01_ALB.uasset
      - ...
      - MI_skin_m_white_07_ALB.uasset

</details>

So when I'm clicking on the `Create LevelSequences` button, I see the next error:

```
LogPython: Error: No asset found for body path: GeometryCache'/Engine/PS/Bedlam/SMPLX/rp_henry_posed_001/rp_henry_posed_001_1071.rp_henry_posed_001_1071'
LogPython: Error: LevelSequence generation failed. Total time: 0.0s
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "C:/Program Files/Epic Games/UE_5.0/Engine/Content/PS/Bedlam/Core/Python/create_level_sequences_csv.py", line 730, in <module>
LogPython: Error:     sys.exit(1)
```
Looks like the script requires a different file structure and different files extensions.
Could you please help me to understand how can I render bodies correctly?

Tranks

**Comment by tpsmpi** [comment]
1. Looks like the desired Alembic GeometryCache file `rp_henry_posed_001_1071` was not imported into Unreal or is at wrong location on your system. You need to have 

`UE_5.0\Engine\Content\PS\Bedlam\SMPLX\rp_henry_posed_001\rp_henry_posed_001_1071.uasset` 

in the filesystem.

2. Your Meshcapade\SMPL textures hierarchy does not seem to follow the instructions. It does not matter for body textures but is important if you want to render clothing overlay textures as used in the `highbmi` renders.
Female textures need to be in: `UE_5.0\Engine\Content\PS\Meshcapade\SMPL\MC_texture_skintones\female\skin`
Male textures need to be in: `UE_5.0\Engine\Content\PS\Meshcapade\SMPL\MC_texture_skintones\male\skin`
